# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: f010513bd2cdf981c7fa6f613df7668982161a4e1816c8db22abe953d7e4ad19438b0e7f5738a924c1ed58e632911b64286233604ea5b5cb51d3f678e103deb3

test:
  secret_key_base: cda504b30a7b0897f8564b2c4e5a5a2eb388388b5149a9847fc3e77bb6d08adb33e023f945fb9c6fd4b170e9a32510d4d3953c309bb0d83fead0777cbbb6bf44

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
